### ISSUE TITLE
Expo installation error: Failed to start (Invariant Violation: Native module cannot be null)

### ISSUE THREAD

**Issue by IgnacioPorte** [adaptyteam/AdaptySDK-React-Native#55]
Hello there, I am trying to do the installation with expo, and currently I have one question and one error.

I am using windows with wsl and these are my dependencies:

```
{
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/native-stack": "^6.9.12",
    "axios": "^1.3.3",
    "expo": "~47.0.12",
    "expo-dev-client": "~2.0.1",
    "expo-linear-gradient": "~12.0.1",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-adapty": "^2.3.13",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-paper": "^5.2.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-typewriter": "^0.7.0",
    "react-native-vector-icons": "^9.2.0"
}
```

1.  Is it necessary to follow this steps to use it with expo? (Use expo-dev-client and make build) Why I can not simply `install react-native-adapty` and run `expo start`

![image](https://user-images.githubusercontent.com/62029630/222984012-c65f5071-8b62-4727-a89f-8d445f147dd0.png)

2. The error I have is that:

  2.1. When I follow the instructions, I have this build error:

  ![image](https://user-images.githubusercontent.com/62029630/222984441-7caba937-efc8-4348-8b86-3b1c1ae56c91.png)

  2.2. When I try to do `install react-native-adapty` and then `expo start`

  ![image](https://user-images.githubusercontent.com/62029630/222984289-99c7a40b-f72d-45b6-9141-cb6d5ebdcf18.png)

  The docs give this solution to the problem, but I don't understand why this would solve the problem

  ![image](https://user-images.githubusercontent.com/62029630/222984359-94db8169-c6b6-4f8d-8ba4-2c7ea9543032.png)

**Comment by divanc** [comment]
Hello, @IgnacioPorte! It is required to follow the documentation steps. I know this sucks, but let me give you a little overview in the following paragraphs so you can understand the reasonings.

The difference between your libraries and Adapty is that Adapty uses native code. For mobile, these are Swift, Objective C, Kotlin, and Java. And we have all of them. It is not something we want but what we need. You cannot have in-app purchases without some native code.

Historically, Expo had no support for in-app purchases, nor native code support. The whole idea behind Expo is building an app with nothing but JS. Expo added native code support (and in-apps) not so long ago with this tedious process you saw in docs. Let's understand what we are doing there.

Usually, you debug (develop) your app in the Expo Go app (I think so). What is it? It's very similar to a browser — an app with a JS engine and React Native bindings installed. So when you do something like `Alert.alert("Hello, mom!")` line of code is passed to a JS engine and then to a native binding, where it is being called.

When you change your JS, you use [Hot Reloading](https://reactnative.dev/blog/2016/03/24/introducing-hot-reloading) to force updated JS code into this browser app. However, there is a problem with doing such a thing with a native code. It compiles into ones and zeros. Not just changed code lines, but an entire project. Every time you update native chunks you re-build your application anew. Building is the farthest you can get from Hot Reloading.

So what did Expo come up with to bring in-app support? It delivered us EAS Builds. Once your native code changes (for example when installing the Adapty library), you need to create a new build to bundle your native code.
```
eas build --profile development --platform ios
```
In this command, you set a specific profile in order to tell Expo, whether you need to payload debug tools. For development, Expo would append that same JS engine and React Native bindings.

After this command is finished you will end up with your own app with the debug "browser" effectively replacing the Expo Go app. This process is not as straightforward as one might hope, but Expo did a fantastic job of making it the most graceful they were able to.

-----

No overload yet? There is one more reason to bring your own app instead of the Expo Go. It is signing. Let us apply it to our domain. Making in-app purchases you should be able to fetch only your own products. It would be rather strange to buy a discounted Tinder subscription from your app, isn't it? Signing helps distributors (Apple and Google) understand your identity. Previously, in development, it always was Expo's identity. It didn't actually matter who you are until you are released. Now, you can identify yourself in development too.

**Comment by divanc** [comment]
About your bug, [maybe this would help](https://github.com/expo/expo/issues/15101#issuecomment-1000405876).

**Comment by IgnacioPorte** [comment]
> Hello, @IgnacioPorte! It is required to follow the documentation steps. I know this sucks, but let me give you a little overview in the following paragraphs so you can understand the reasonings.
> 
> The difference between your libraries and Adapty is that Adapty uses native code. For mobile, these are Swift, Objective C, Kotlin, and Java. And we have all of them. It is not something we want but what we need. You cannot have in-app purchases without some native code.
> 
> Historically, Expo had no support for in-app purchases, nor native code support. The whole idea behind Expo is building an app with nothing but JS. Expo added native code support (and in-apps) not so long ago with this tedious process you saw in docs. Let's understand what we are doing there.
> 
> Usually, you debug (develop) your app in the Expo Go app (I think so). What is it? It's very similar to a browser — an app with a JS engine and React Native bindings installed. So when you do something like `Alert.alert("Hello, mom!")` line of code is passed to a JS engine and then to a native binding, where it is being called.
> 
> When you change your JS, you use [Hot Reloading](https://reactnative.dev/blog/2016/03/24/introducing-hot-reloading) to force updated JS code into this browser app. However, there is a problem with doing such a thing with a native code. It compiles into ones and zeros. Not just changed code lines, but an entire project. Every time you update native chunks you re-build your application anew. Building is the farthest you can get from Hot Reloading.
> 
> So what did Expo come up with to bring in-app support? It delivered us EAS Builds. Once your native code changes (for example when installing the Adapty library), you need to create a new build to bundle your native code.
> 
> ```
> eas build --profile development --platform ios
> ```
> 
> In this command, you set a specific profile in order to tell Expo, whether you need to payload debug tools. For development, Expo would append that same JS engine and React Native bindings.
> 
> After this command is finished you will end up with your own app with the debug "browser" effectively replacing the Expo Go app. This process is not as straightforward as one might hope, but Expo did a fantastic job of making it the most graceful they were able to.
> 
> No overload yet? There is one more reason to bring your own app instead of the Expo Go. It is signing. Let us apply it to our domain. Making in-app purchases you should be able to fetch only your own products. It would be rather strange to buy a discounted Tinder subscription from your app, isn't it? Signing helps distributors (Apple and Google) understand your identity. Previously, in development, it always was Expo's identity. It didn't actually matter who you are until you are released. Now, you can identify yourself in development too.

Thanks for the answer, I didn't expect them to answer so quickly, everything was much clearer to me, the only question I have is if every time I change code that doesn't use native modules I'll still have to do a build, or it would work like a hot reload but only for the js code

**Comment by divanc** [comment]
Hope this helps! 

I only need to re-build when native code changes. I know how difficult it might sound right now!

Basically, if this is the first time you've heard about EAS, then you only need to make a new build when updating Adapty library to newer version. If a library has native code in GitHub preview (image below) or their docs mention EAS, then you probably need to make a build, when adding one

<img width="277" alt="image" src="https://user-images.githubusercontent.com/16625670/223143917-6e406826-3338-40bc-ae66-a3dbbb113a54.png">

I haven't released an Expo app to production for quite a while, but I also bet, that you have to build a production build via EAS now

@IgnacioPorte

**Comment by IgnacioPorte** [comment]
I struggled a lot to make the build, but I got it, thanks again for taking the time to explain. 😀

**Comment by divanc** [comment]
> I struggled a lot to make the build, but I got it, thanks again for taking the time to explain. 😀

It's quite steep to learn, but it gets easier. Congrats!
