### ISSUE TITLE
Product Purchase Failed on Cancel

### ISSUE THREAD

**Issue by HaseebArshad1** [adaptyteam/AdaptySDK-React-Native#69]
### Description

A bug happened!

Hey @divanc, I just faced this issue recently is this something expected? because whenever I'm trying to close the payment modal it shows me this error:

```
}, NSLocalizedFailureReason=Payment sheet dismissed with neither an error nor a result}}}}})", "message": "Product purchase failed"}
 DEBUG  [2023-04-28T06:51:07.534Z] [adapty@2.4.5] "makePurchase": Calling method: OK {"error": [Error: #1006 (productPurchaseFailed): Product purchase failed]}
```

The payment was cancelled by the user and it was expected since the user press cross icon but why `Product purchase failed` error is being triggered. Can you please check? Thanks!

### Version

v2.3.5

### What platforms are you seeing the problem on?

iOS

### System info

```yml
iOS: 16.4.1
Device: iPhone 14 pro max
```

**Comment by divanc** [comment]
Hello! It is an error in the world of digital purchases set by Apple and Google StoreKits. We intend to remain it this way, so the code flow remains simple: 
- if promise resolves, it means a purchase was a success
- if promise rejects, it means a purchase was not completed

It allows you (a developer) to handle cancellation separately.

Still your issue is valid, since current code does not properly signal you what has happened. It meant to be a separate code (error code 2) and our next release should fix that. In that manner it duplicates #63

**Comment by HaseebArshad1** [comment]
@divanc Oh Okay, Thanks! I'm closing this ticket! Waiting for the update. 🙌
