### ISSUE TITLE
Do you support React Native's fabric new architecture?

### ISSUE THREAD

**Issue by the-skins-app** [adaptyteam/AdaptySDK-React-Native#70]
### Description

If not, any idea when you will?

**Comment by divanc** [comment]
Hello, @the-skins-app!
Currently, we do not. I'm not an expert in this question, so you can guide my mistakes. You probably questioning upgrading to `TurboModules`, since Fabric is a renderer of views and components.

To my knowledge both `TurboModules` and `Fabric Components` are still both experimental and both unstable.
Were there any updates recently that I've skipped?  

Since we cannot raise a minimal supported RN version from 0.60, we need to do some kind of metaprogramming. It would ensure that users would have buildable projects with react-native below v0.68.
I don't currently know a way to achieve this in Kotlin/Java... 

I'm interested in this feature, but that would not be a priority task, because of unsteady APIs.

I will study the possibilities to implement this and will try to incrementally add features to support new archs

No ETAs for now

**Comment by divanc** [comment]
I've created [a discussion for that](https://github.com/adaptyteam/AdaptySDK-React-Native/discussions/71) that you can follow. Seems more fitting for the case

**Comment by divanc** [comment]
I'd close issue as replaced with a discussion for now

**Comment by AdamGerthel** [comment]
Is this still not implemented? I was just about to move from React Native IAP to Adapty but if the new arch isn't supported, then it's a no-go.
