### ISSUE TITLE
Best practice for adapty.activate 

### ISSUE THREAD

**Issue by WrathChaos** [adaptyteam/AdaptySDK-React-Native#83]
### Description

![CleanShot 2023-08-17 at 18 53 14](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/6813862/2f155a32-3045-4b58-ab28-3d7700fa0032)
https://docs.adapty.io/docs/react-native-configuring#delaying-sdk-activation

As it says on this documentation, `Preferably, place activation before React component ` however, if I am doing this there is a problem for async-await warning.

![CleanShot 2023-08-17 at 18 54 29](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/6813862/9af24b21-43b7-4e16-b57c-8dd362d35258)

How should we do it properly with the new `2.6.0`? 

Thank you 🍻

**Comment by divanc** [comment]
Merhaba, Ogün!
Documentation displays a simple workable example, but your analysis tool is right _(kind of)_!
The thing is `activate` can actually throw, and that's what your linter is concerned about. You see, some errors might kill your app, if unhandled. In RN debug it looks like unclosable black&red box, in prod — app just quits.

> P.S. I'm not intimately familiar with how RN runtime works, but if we consider it works the same way as Node, then uncaught **promise** error like `activate` call _**SHOULDN'T**_ terminate your app, they should only result into a console.error. 

While we provide several possible errors in activation, the only activation error I've seen in years is when you provide invalid public API key. Hence, nothing in Adapty SDK would work.

You can choose to just wrap it into a catching function and work with it how you like, but you will probably still need to suppress this rule for one line, depending on how your tool decides what to warn. (it might be due to JSDoc `@throws` directive in `activate`)

```ts
async function activateSdks() {
  try {
    await adapty.activate(...)
    ...
  } catch (error) {
    // msg to Slack?
  }
}


// before core component
// LINTER SUPRESS UNHANDLED EXCEPTION
activateSdks();
```

You also can just imitate a sync function, so that your linter does not know it can reject, but you should be very cautious about how this code is interpreted by computer and other programmers:
```
function promiseToActivateSdks() {
  adapty.activate(...);
  // try-catch wouldn't work here
}

// before core component
promiseToActivateSdks();
```

@WrathChaos

**Comment by divanc** [comment]
Please, re-open this issue, if this question is still unanswered to you!
